#!/usr/bin/env bash
# This script transfers a file from the client to a server

if [ "$#" -ne 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assigning paramentals to variables
PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Ensure the private key file has the correct permissions
chmod 600 "$PATH_TO_SSH_KEY"

# Disabbling strict host key checking
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@SERVER_IP:~/"

# Checking if the transfer was successful
if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
	exit 1
fi
