#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# Nginx should be listening on port 80 and serve a page that return "Hello World"

# Function to display messages
log() {
	echo -e "\n$1\n"
}

log "Updating package lists and installing Nginx."
sudo apt-get update -y -qq && sudo apt-get install nginx -y -qq

log "Starting Nginx service."
sudo service nginx start

log "Allowing Nginx HTTP through the firewall."
sudo ufw allow 'Nginx HTTP'

log "Backing up the default Nginx index page."
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

log "Creating a new index page with 'Hello World!' content."
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

log "Restarting Nginx service."
sudo service nginx restart

log "Configuration completed.\n"
