#!/usr/bin/env bash
sudo sed -i 's/listen 8080 default_server/listen 80 default_server/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:8080 default_server/listen \[::\]:80 default_server/' /etc/nginx/sites-available/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
