#!/usr/bin/env bash
# This script creates an RSA key pair named 'school' with 4096 bits and a passphrase 'betty'

#Define the key filename
KEY_NAME="school"
PASSPHRASE="betty"

# Remove any existing key with the same name
rm -f ~/.ssh/$KEY_NAME ~/.ssh/$KEY_NAME.pub

# Generate the RSA pair
ssh-keygen -t rsa -b 4096 -f ~/.ssh/$KEY_NAME -N "$PASSPHRASE"
